@extends('admin.layouts.app')
@section('page-title', $notice->exists ? 'Edit Meeting Notice' : 'New Meeting Notice')
@section('page-subtitle', 'Publish a clear notice for members and visitors')
@section('content')
<div class="card"><div class="card-body"><form method="POST" action="{{ $notice->exists ? route('admin.meeting-notices.update', $notice) : route('admin.meeting-notices.store') }}">@csrf @if($notice->exists) @method('PUT') @endif
<div class="row"><div class="col-md-8 mb-3"><label class="form-label">Title *</label><input name="title" class="form-control" required value="{{ old('title', $notice->title) }}"></div><div class="col-md-4 mb-3"><label class="form-label">Meeting type</label><input name="meeting_type" class="form-control" value="{{ old('meeting_type', $notice->meeting_type) }}"></div></div>
<div class="mb-3"><label class="form-label">Summary *</label><textarea name="summary" class="form-control" rows="3" required>{{ old('summary', $notice->summary) }}</textarea></div>
<div class="mb-3"><label class="form-label">Details</label><textarea name="details" class="form-control" rows="5">{{ old('details', $notice->details) }}</textarea></div>
<div class="row"><div class="col-md-4 mb-3"><label class="form-label">Starts at *</label><input type="datetime-local" name="starts_at" class="form-control" required value="{{ old('starts_at', $notice->starts_at?->format('Y-m-d\\TH:i')) }}"></div><div class="col-md-4 mb-3"><label class="form-label">Ends at</label><input type="datetime-local" name="ends_at" class="form-control" value="{{ old('ends_at', $notice->ends_at?->format('Y-m-d\\TH:i')) }}"></div><div class="col-md-4 mb-3"><label class="form-label">Priority</label><input type="number" name="priority" class="form-control" min="0" value="{{ old('priority', $notice->priority ?: 0) }}"></div></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Location</label><input name="location" class="form-control" value="{{ old('location', $notice->location) }}"></div><div class="col-md-3 mb-3"><label class="form-label">Action label</label><input name="action_label" class="form-control" value="{{ old('action_label', $notice->action_label) }}"></div><div class="col-md-3 mb-3"><label class="form-label">Action URL</label><input type="url" name="action_url" class="form-control" value="{{ old('action_url', $notice->action_url) }}"></div></div>
<div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" @checked(old('is_active', $notice->exists ? $notice->is_active : true))><label class="form-check-label" for="is_active">Active on public site</label></div><div class="form-check mb-4"><input class="form-check-input" type="checkbox" name="show_popup" value="1" id="show_popup" @checked(old('show_popup', $notice->exists ? $notice->show_popup : true))><label class="form-check-label" for="show_popup">Show as a popup after the site loads</label></div>
<button class="btn btn-primary">Save notice</button> <a class="btn btn-secondary" href="{{ route('admin.meeting-notices.index') }}">Cancel</a>
</form></div></div>
@endsection
