@extends('admin.layouts.app')
@section('page-title', $realization->exists ? 'Edit Monthly Realization' : 'New Monthly Realization')
@section('page-subtitle', 'Celebrate a community achievement')
@section('content')
<div class="card"><div class="card-body"><form method="POST" enctype="multipart/form-data" action="{{ $realization->exists ? route('admin.monthly-realizations.update', $realization) : route('admin.monthly-realizations.store') }}">@csrf @if($realization->exists) @method('PUT') @endif
<div class="row"><div class="col-md-4 mb-3"><label class="form-label">Month *</label><input type="date" name="month" class="form-control" required value="{{ old('month', $realization->month?->format('Y-m-d')) }}"></div><div class="col-md-8 mb-3"><label class="form-label">Title *</label><input name="title" class="form-control" required value="{{ old('title', $realization->title) }}"></div></div>
<div class="row"><div class="col-md-7 mb-3"><label class="form-label">Community / association *</label><input name="community_name" class="form-control" required value="{{ old('community_name', $realization->community_name) }}"></div><div class="col-md-3 mb-3"><label class="form-label">LGA</label><input name="lga" class="form-control" value="{{ old('lga', $realization->lga) }}"></div><div class="col-md-2 mb-3"><label class="form-label">Priority</label><input type="number" name="priority" class="form-control" min="0" value="{{ old('priority', $realization->priority ?: 0) }}"></div></div>
<div class="mb-3"><label class="form-label">Summary *</label><textarea name="summary" class="form-control" rows="3" required>{{ old('summary', $realization->summary) }}</textarea></div><div class="mb-3"><label class="form-label">Details</label><textarea name="details" class="form-control" rows="5">{{ old('details', $realization->details) }}</textarea></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Impact metric</label><input name="impact_metric" class="form-control" placeholder="e.g. 5 LGAs represented" value="{{ old('impact_metric', $realization->impact_metric) }}"></div><div class="col-md-6 mb-3"><label class="form-label">Image (optional)</label><input type="file" name="image" class="form-control" accept="image/jpeg,image/png,image/webp">@if($realization->image)<small>Current image: {{ $realization->image }}</small>@endif</div></div>
<div class="form-check mb-4"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" @checked(old('is_active', $realization->exists ? $realization->is_active : true))><label class="form-check-label" for="is_active">Show on the public site</label></div>
<button class="btn btn-primary">Save realization</button> <a class="btn btn-secondary" href="{{ route('admin.monthly-realizations.index') }}">Cancel</a>
</form></div></div>
@endsection
